### ISSUE TITLE
Scrub Suggestions

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#71] opened 2020-03-04 18:11 UTC
When I first started out with Benji and a small amount of RBD volumes, I would deep scrub each new version every night.  Now that my RBD volumes has increased it just doesn't seem possible to do that anymore.  

Any suggestions on how often I should run a scrub?  Maybe I should just use a normal scrub?  

Appreciate any input or suggestions!

**Comment by adambmedent** [comment] 2020-03-10 10:50
Starting to worry this project is otw to being dead?

**Comment by elemental-lf** [comment] 2020-03-10 12:16
Oh, no, the project is not dead at all, you're just too impatient. I've been investing most of my spare time into getting the Kubernetes operator into a state where I dare to merge it into master. Benji itself seems to run along quite well.

Regarding your questions:

* You can supply `--block-percentage` to `benji deep-scrub` to only scrub a statistically sampled subset of the blocks. `benji scrub` supports the same option. A deep-scrub is expensive by design as it reads the blocks from storage.
* I would suggest to use `benji batch-deep-scrub` with `--version-percentage` and/or `--block-percentage` to scrub a subset of your versions each day. If you check 15% of the versions each day you'll be (statistically) checking all versions once a week. This is what really protects against bit-rot as it also scrubs older versions.
* You could try to play with the number of simultaneous readers and see if this speeds up the deep-scrub.
* Scrubs can run in parallel to backups. You can implement them as a separate process or put them at the end of your daily backup run.

**Comment by adambmedent** [comment] 2020-03-10 17:52
Appreciate the input.  

Good to know scrubs can run in parallel of the backups, but I am sure it will effect performance while the backups run.   

I have been seeing the best performance with 3-5 read threads. 

A bit confused on only scrubbing a percentage of versions per day, each day new versions are added, I don't really see how it can keep up.  At this point I have 60 RBD's I am backing up with Benji and am struggling to deep-scrub each nightly version.  

Would it make more sense to deep-scrub only 1 of the 7 versions per RBD a week?

**Comment by elemental-lf** [comment] 2020-03-11 13:30
It really depends a lot on your environment. With a given retention policy you should reach some steady state concerning the number of versions after some time. In addition the number of blocks should fluctuate less from that point on. So you can tune your deep-scrubs with that as the base line, also taking into account the time available each day, parallel backups and other performance concerns. If the number of versions you can scrub each day that way goes below the service level you have set for durability and reliability you need to see if you can tune or upgrade other variables to reach it again.

`benji batch-deep-scrub` is the right tool for the job.  My suggestion is to scrub a certain percentage of all existing versions each day because it also checks older versions. But you could also batch scrub only the new versions by specifying a filter expression (`uid == "x" or uid == "y" or uid == "z"` or by setting a label with a unique value and filtering on that). The advantage of `benji batch-deep-scrub` is that it will only scrub each block once even if it is used by multiple versions of the scrub run.

**Comment by elemental-lf** [comment] 2020-03-19 11:53
I'm going to close this issue. If you've any further questions please open a new one. Thanks!

**Closed as completed by elemental-lf** 2020-03-19 11:53 UTC
Labels: user support
