### ISSUE TITLE
Retention removed version it shouldn't have

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#37] opened 2019-04-08 11:48 UTC
I believe I hit a bug.  Finally got a larger scale test going.  15 rbd volumes being backed up nightly by benji.  

The first backup I did manually, the rest were scheduled via cron.

| 2019-04-05T10:39:05 | V0000000199 | vm-114-disk-0 | set-a-2019-04-05T10:39:02 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-06T00:08:35 | V0000000214 | vm-114-disk-0 | set-a-2019-04-06T00:08:32 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-07T00:08:35 | V0000000229 | vm-114-disk-0 | set-a-2019-04-07T00:08:32 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-08T00:08:35 | V0000000244 | vm-114-disk-0 | set-a-2019-04-08T00:08:33 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
+---------------------+-------------+---------------+---------------------------+----------+------------+--------+-----------+---------+

I ran a enforce which was 

/usr/local/benji/bin/benji enforce latest1,days14,months17

Which resulted in.

| 2019-04-05T09:50:19 | V0000000139 | vm-114-disk-0 | set-a-2019-04-05T09:50:17 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-07T00:08:35 | V0000000229 | vm-114-disk-0 | set-a-2019-04-07T00:08:32 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-08T00:08:35 | V0000000244 | vm-114-disk-0 | set-a-2019-04-08T00:08:33 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
+---------------------+-------------+---------------+---------------------------+----------+------------+--------+-----------+---------+

So for whatever reason it removed V0000000214 which was my 04-06 daily snapshot.  

I should also say when running a dry run, its very hard to interpret the output in such a way to make a quick decision on whats being deleted.  Is there any way to list each version with its corresponding date line by line?

**Comment by elemental-lf** [comment] 2019-04-09 09:51
I'll need to revisit the retention algorithm. This will take some time.

**Comment by adambmedent** [comment] 2019-04-09 11:13
Sounds good, let me know if there is anything I can do to test for you.  

I think I am hitting another issue as well, but I am not totally sure.

| 2019-04-05T09:50:19 | V0000000139 | vm-114-disk-0 | set-a-2019-04-05T09:50:17 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-07T00:08:35 | V0000000229 | vm-114-disk-0 | set-a-2019-04-07T00:08:32 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-08T00:08:35 | V0000000244 | vm-114-disk-0 | set-a-2019-04-08T00:08:33 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-08T10:50:48 | V0000000259 | vm-114-disk-0 | set-a-2019-04-08T10:50:45 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-09T00:09:07 | V0000000274 | vm-114-disk-0 | set-a-2019-04-09T00:09:05 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
+---------------------+-------------+---------------+---------------------------+----------+------------+--------+-----------+---------+

Running the same enforce command

/usr/local/benji/bin/benji enforce latest1,days14,months17 --dry-run

I have two backups on 4/8 within 12 hours of each other. It seems like it should be removing at least one of them?  It reports all versions conforming to the retention policy.

**Comment by adambmedent** [comment] 2019-04-10 15:33
Interesting enough, when running the enforcement command today, it now wants to remove the 4/8 snaps from the 10:50am like I would expect.   Is it because they weren't quite a day old yet when I ran the enforce yesterday?

**Comment by elemental-lf** [comment] 2019-04-10 18:38
Hmm, that could be the case as the retention algorithm isn't working on date boundaries but is calculating backwards from the current point in time (interval ]-24h, 0h] for the zero-th day back, ]-48h,-24h] for the first day back and so on) and it is keeping the oldest version in each class as explained.

**Comment by adambmedent** [comment] 2019-04-10 19:21
> Hmm, that could be the case as the retention algorithm isn't working on date boundaries but is calculating backwards from the current point in time (interval ]-24h, 0h] for the zero-th day back, ]-48h,-24h] for the first day back and so on) and it is keeping the oldest version in each class as explained.

That does seem to make more sense with what I am seeing.  First issue I posted still stands though, that it removed a day it shouldn't have.  Interested to see what you end up pinning down, good luck!

**Comment by adambmedent** [comment] 2019-04-18 14:06
Just wanted to report in, still haven't hit the issue I originally reported.  I am at 12/14 daily snaps, so Sunday I should start seeing some snapshots getting cleaned up.

**Comment by adambmedent** [comment] 2019-04-22 11:34
Finally hit my 14 days worth of versions.  Here are the versions I currently have.  

+---------------------+-------------+---------------+---------------------------+----------+------------+--------+-----------+---------+
|         date        |     uid     | name          | snapshot_name             |     size | block_size | status | protected | storage |
+---------------------+-------------+---------------+---------------------------+----------+------------+--------+-----------+---------+
| 2019-04-04T08:57:40 | V0000000118 | vm-100-disk-0 | set-a-2019-04-04T08:57:38 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-05T09:36:52 | V0000000125 | vm-100-disk-0 | set-a-2019-04-05T09:36:49 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-07T00:05:05 | V0000000215 | vm-100-disk-0 | set-a-2019-04-07T00:05:02 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-08T00:05:05 | V0000000230 | vm-100-disk-0 | set-a-2019-04-08T00:05:02 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-09T00:05:05 | V0000000260 | vm-100-disk-0 | set-a-2019-04-09T00:05:02 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-10T00:05:05 | V0000000275 | vm-100-disk-0 | set-a-2019-04-10T00:05:02 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-11T00:05:05 | V0000000290 | vm-100-disk-0 | set-b-2019-04-11T00:05:03 | 100.0GiB |     4.0MiB | valid  |   False   | set-b   |
| 2019-04-12T00:05:04 | V0000000305 | vm-100-disk-0 | set-b-2019-04-12T00:05:02 | 100.0GiB |     4.0MiB | valid  |   False   | set-b   |
| 2019-04-13T00:05:05 | V0000000320 | vm-100-disk-0 | set-a-2019-04-13T00:05:02 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-14T00:05:05 | V0000000335 | vm-100-disk-0 | set-a-2019-04-14T00:05:03 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-15T00:05:05 | V0000000350 | vm-100-disk-0 | set-b-2019-04-15T00:05:02 | 100.0GiB |     4.0MiB | valid  |   False   | set-b   |
| 2019-04-16T00:05:05 | V0000000365 | vm-100-disk-0 | set-b-2019-04-16T00:05:02 | 100.0GiB |     4.0MiB | valid  |   False   | set-b   |
| 2019-04-17T00:05:07 | V0000000380 | vm-100-disk-0 | set-b-2019-04-17T00:05:04 | 100.0GiB |     4.0MiB | valid  |   False   | set-b   |
| 2019-04-18T00:05:05 | V0000000395 | vm-100-disk-0 | set-b-2019-04-18T00:05:02 | 100.0GiB |     4.0MiB | valid  |   False   | set-b   |
| 2019-04-19T00:05:05 | V0000000410 | vm-100-disk-0 | set-a-2019-04-19T00:05:02 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-20T00:05:05 | V0000000425 | vm-100-disk-0 | set-a-2019-04-20T00:05:02 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-21T00:05:05 | V0000000440 | vm-100-disk-0 | set-a-2019-04-21T00:05:03 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |
| 2019-04-22T00:05:04 | V0000000455 | vm-100-disk-0 | set-a-2019-04-22T00:05:02 | 100.0GiB |     4.0MiB | valid  |   False   | set-a   |

/usr/local/benji/bin/benji -m enforce latest1,days14,months17 --dry-run

Running the above command and the only versions benji wants to get rid of is V0000000125 and V0000000215.  

I believe it should get rid of version V0000000118 and V0000000230 as well?

**Comment by elemental-lf** [comment] 2019-04-23 13:31
@adambmedent sorry, I didn't have the time to look into this yet. Could you provide the output of `enforce` with `--log-level DEBUG`? This should give me some more information to work with?

**Comment by adambmedent** [comment] 2019-04-23 13:52
Not having much luck just adding that option.  Is there something else I need to do?

(benji) [root@ceph-backups ~]# /usr/local/benji/bin/benji enforce latest1,days14,months17 --log-level DEBUG --dry-run
usage: benji [-h] [-c CONFIG_FILE] [-m]
             [--log-level {DEBUG,INFO,WARNING,ERROR}] [--no-color]
             {backup,batch-deep-scrub,batch-scrub,cleanup,completion,database-init,database-migrate,deep-scrub,enforce,label,ls,metadata-backup,metadata-export,metadata-import,metadata-ls,metadata-restore,nbd,protect,restore,rm,scrub,storage-stats,unprotect,version-info}
             ...
benji: error: unrecognized arguments: --log-level DEBUG

**Comment by elemental-lf** [comment] 2019-04-23 20:19
You have to put it between `benji` and `enforce` as it is a global option and not subcommand specific. Maybe I should change this behaviour, but that's the way it currently is. 
I think when I'm going to look into this, I'm going to add some tests, too. And I might have an idea what goes wrong here actually.

**Comment by adambmedent** [comment] 2019-04-24 10:52
Ahh I knew I was missing something, I should have given that a try.  

Here is the debug output for the one volume i am using as an example in this post.  

   DEBUG: Current database schema revision: 368014edd88c.
   DEBUG: Expected database schema revision: 368014edd88c.
   DEBUG: Retention filter set up with reference time 1556102850.3632946 and rules OrderedDict([('latest', 1), ('days', 14), ('months', 17)])
   DEBUG: Keeping 1 latest versions.
   DEBUG: Time and time delta for version V0000000470 are 2019-04-23 04:05:04.959948 and _Timedelta(days=1, hours=30, months=0, weeks=0, years=0).
   DEBUG: Found matching category days, timecount 1.
   DEBUG: Time and time delta for version V0000000455 are 2019-04-22 04:05:04.985738 and _Timedelta(days=2, hours=54, months=0, weeks=0, years=0).
   DEBUG: Found matching category days, timecount 2.
   DEBUG: Time and time delta for version V0000000440 are 2019-04-21 04:05:05.897583 and _Timedelta(days=3, hours=78, months=0, weeks=0, years=0).
   DEBUG: Found matching category days, timecount 3.
   DEBUG: Time and time delta for version V0000000425 are 2019-04-20 04:05:05.242120 and _Timedelta(days=4, hours=102, months=0, weeks=0, years=0).
   DEBUG: Found matching category days, timecount 4.
   DEBUG: Time and time delta for version V0000000410 are 2019-04-19 04:05:05.373408 and _Timedelta(days=5, hours=126, months=0, weeks=0, years=0).
   DEBUG: Found matching category days, timecount 5.
   DEBUG: Time and time delta for version V0000000395 are 2019-04-18 04:05:05.252062 and _Timedelta(days=6, hours=150, months=0, weeks=0, years=0).
   DEBUG: Found matching category days, timecount 6.
   DEBUG: Time and time delta for version V0000000380 are 2019-04-17 04:05:07.485794 and _Timedelta(days=7, hours=174, months=0, weeks=1, years=0).
   DEBUG: Found matching category days, timecount 7.
   DEBUG: Time and time delta for version V0000000365 are 2019-04-16 04:05:05.722790 and _Timedelta(days=8, hours=198, months=0, weeks=1, years=0).
   DEBUG: Found matching category days, timecount 8.
   DEBUG: Time and time delta for version V0000000350 are 2019-04-15 04:05:05.545023 and _Timedelta(days=9, hours=222, months=0, weeks=1, years=0).
   DEBUG: Found matching category days, timecount 9.
   DEBUG: Time and time delta for version V0000000335 are 2019-04-14 04:05:05.844858 and _Timedelta(days=10, hours=246, months=0, weeks=1, years=0).
   DEBUG: Found matching category days, timecount 10.
   DEBUG: Time and time delta for version V0000000320 are 2019-04-13 04:05:05.503072 and _Timedelta(days=11, hours=270, months=0, weeks=1, years=0).
   DEBUG: Found matching category days, timecount 11.
   DEBUG: Time and time delta for version V0000000305 are 2019-04-12 04:05:04.839690 and _Timedelta(days=12, hours=294, months=0, weeks=1, years=0).
   DEBUG: Found matching category days, timecount 12.
   DEBUG: Time and time delta for version V0000000290 are 2019-04-11 04:05:05.592787 and _Timedelta(days=13, hours=318, months=0, weeks=1, years=0).
   DEBUG: Found matching category days, timecount 13.
   DEBUG: Time and time delta for version V0000000275 are 2019-04-10 04:05:05.803325 and _Timedelta(days=14, hours=342, months=0, weeks=2, years=0).
   DEBUG: Found matching category days, timecount 14.
   DEBUG: Time and time delta for version V0000000260 are 2019-04-09 04:05:05.642349 and _Timedelta(days=15, hours=366, months=0, weeks=2, years=0).
   DEBUG: Found matching category months, timecount 0.
   DEBUG: Time and time delta for version V0000000230 are 2019-04-08 04:05:05.117527 and _Timedelta(days=16, hours=390, months=0, weeks=2, years=0).
   DEBUG: Found matching category months, timecount 0.
   DEBUG: Time and time delta for version V0000000215 are 2019-04-07 04:05:05.399299 and _Timedelta(days=17, hours=414, months=0, weeks=2, years=0).
   DEBUG: Found matching category months, timecount 0.
   DEBUG: Time and time delta for version V0000000125 are 2019-04-05 13:36:52.136762 and _Timedelta(days=18, hours=453, months=0, weeks=2, years=0).
   DEBUG: Found matching category months, timecount 0.
   DEBUG: Time and time delta for version V0000000118 are 2019-04-04 12:57:40.508085 and _Timedelta(days=19, hours=477, months=0, weeks=2, years=0).
   DEBUG: Found matching category months, timecount 0.
   DEBUG: Retention filter set up with reference time 1556102850.3758392 and rules OrderedDict([('latest', 1), ('days', 14), ('months', 17)])
   DEBUG: Keeping 1 latest versions.

**Comment by elemental-lf** [comment] 2019-05-07 09:17
@adambmedent in the case that you're feeling adventurous today, there's a work in progress overhaul of the retention algorithm in this branch: https://github.com/elemental-lf/benji/tree/fix-retentionfilter. Apart from hopefully fixing the algorithm it also changes it so that all categories align to calendar boundaries (start of hour, day, week, etc.) . This should make it more comprehensible and it should be easier to spot problems in the future. For this to work the time zone  needs to be set up correctly.

**Comment by adambmedent** [comment] 2019-05-07 12:37
Awesome, appreciate all the hard work.  Whats the best way to apply that branch?  Would I just do the following?

pip install git+https://github.com/elemental-lf/benji/tree/fix-retentionfilter

**Comment by elemental-lf** [comment] 2019-05-07 19:39
I think the syntax for `pip` is:
```bash
pip install git+https://github.com/elemental-lf/benji@fix-retentionfilter
```

**Comment by elemental-lf** [comment] 2019-05-09 09:34
@adambmedent I'm now testing `fix-retentionfilter` in a real-life setup. Due to the newly introduced alignment on calendar boundaries it is much easier to see if the policy works as intended or not. And it's looking good so far. So if you haven't got around to test the branch, now would be a good time! 😊 Thank you!

**Comment by adambmedent** [comment] 2019-05-09 10:57
> @adambmedent I'm now testing `fix-retentionfilter` in a real-life setup. Due to the newly introduced alignment on calendar boundaries it is much easier to see if the policy works as intended or not. And it's looking good so far. So if you haven't got around to test the branch, now would be a good time! 😊 Thank you!

After running the pip command I did run the enforcement and all looked good.  However my last night benji run was a complete fail.  

All of them failed with a error similar to this.

The supplied URL rbd://Test/vm-100-disk-0@set-b-2019-05-09T00:05:02 is invalid.

The URL does indeed exist so I am not really sure what went wrong.  Just tried a manual one and I an getting the same error.  

ERROR: UsageError: The supplied URL rbd://Test/vm-100-disk-0@set-a-2019-05-09T06:45:16 is invalid

[root@ceph-backups tmp]# rbd snap ls Test/vm-100-disk-0
SNAPID NAME                        SIZE TIMESTAMP                
  1532 set-b-2019-05-09T00:05:02 100GiB Thu May  9 00:05:03 2019 
  1562 set-a-2019-05-09T06:45:16 100GiB Thu May  9 06:45:16 2019

Any idea what that error means?

**Comment by adambmedent** [comment] 2019-05-09 15:17
I was able to get back to a good state by simply doing.

pip install benji==0.5.0

If I run this again, I am back to the error posted above

pip install git+https://github.com/elemental-lf/benji@fix-retentionfilter

**Comment by elemental-lf** [comment] 2019-05-09 19:00
My bad, see https://github.com/elemental-lf/benji/issues/39. I switched to a more standards compliant URL parsing. Just remove the two slashes after the `rbd:`.

**Comment by adambmedent** [comment] 2019-05-10 13:31
Rocking and rolling now, appreciate the input.  

Ill report back on the new retention fix.  So far its looking good.

**Comment by elemental-lf** [comment] 2019-05-20 11:04
@adambmedent I've just merged the `fix-retentionfilter` branch into master. How has your experience been so far?

**Comment by adambmedent** [comment] 2019-05-20 13:54
So far I haven't hit any other issues.  Looking good!

**Comment by elemental-lf** [comment] 2019-05-22 07:29
Thanks for the feedback! It's great to hear that it's running well for you now. I am going to close this issue.

**Closed as completed by elemental-lf** 2019-05-22 07:29 UTC
Labels: bug
