### ISSUE TITLE
Benji enforce policy question

### ISSUE THREAD

**Issue by kvaps** [elemental-lf/benji#78] opened 2020-05-13 08:07 UTC
Hi, I I have dynamic environment where new VM are creating and deleting any time. I need to keep backups only for existing VMs and remove them by retention policy if VM is not exists anymore.

I found:

```
benji enforce months1
```
very useful, but I need to keep last 3 backups per month, and remove anything else. Eg something like that:

```
benji enforce 3months1
``` 
or
```
benji enforce months1,months1,months1
```
would be so useful

**Comment by elemental-lf** [comment] 2020-05-14 09:29
To clarify: You want to retain three versions per month for the last three months? (As a workaround you could use `weeks12` which is four versions per month for the last three months.)

**Comment by elemental-lf** [comment] 2020-05-14 10:08
At first glance this should easily be possible without any fundamental changes by keeping the desired number of versions instead of only one in this code segment. To make it backwards compatible and the configuration syntax even more byzantine the configuration would be `3months3` meaning: Retain three versions (the first number `3`)  for each month for the last three months (the second number `3`).

https://github.com/elemental-lf/benji/blob/7e714f853a7a30705f7a1643d7838969da6f05d7/src/benji/retentionfilter.py#L141-L143

Could you tell me more about your use case please? And why `weeks12` wouldn't be a suitable alternative? I'm trying to evaluate if such a new feature would be generally useful as it would introduced extra complexity into a sensitive area.

EDIT: Fix typo.

**Comment by kvaps** [comment] 2020-05-14 10:48
Heh, I also a bit confused what the difference between

```
benji enforce weeks1,latest1
```
and
```
benji enforce days7,latest1
```

`weeks1` is doning nothing in my case:
```
    INFO: All versions are conforming to the retention policy.
```

but `days7` is going to remove a lot of copies, including `one-vm-6396-disk-2-urti2a`:
```
benji ls | grep one-vm-6396-disk-2
| 2020-05-06T02:28:23 | one-vm-6396-disk-2-urti2a | one-vm-6396-disk-2 |          | 100.0GiB |     4.0MiB |   valid    |   False   | storage10-s3 |
| 2020-05-13T07:46:55 | one-vm-6396-disk-2-xmpdwz | one-vm-6396-disk-2 |          | 100.0GiB |     4.0MiB |   valid    |   False   | storage10-s3 |
```

**Comment by elemental-lf** [comment] 2020-05-14 11:47
Without seeing all the versions I can't tell you why this specific version would be removed. But I can explain the intended behaviour of the two specifications you listed:

- `weeks1,latest1`: Keep the youngest version and keep one version of the current week. This results in up to two remaining versions of a specific volume (apart from protected and incomplete versions which are not taken into account).
- `days7,latest1`: Keep the youngest version and keep one version per day for the last seven days. This results in up to eight remaining versions.

The order of categories is irrelevant. It's always: `latest`, `hours`, `days`, `weeks`, `months`, `years`. Versions are sorted into buckets resulting from the specification. `latest` is special because it has no associated time interval and only looks for the youngest versions.

For example `latest3,weeks2,months1` would generate four buckets: 

1. `latest`: Keep the youngest three versions in this bucket.
2. `weeks3`, time interval of the current week: Put all versions matching this interval into this bucket and keep exactly one version of this bucket (the oldest).
3. `weeks3`, time interval of the last week: Same as 2. with a different interval.
4. `months1`, time interval of the current month: Same as 2. with a different interval.

Versions are first grouped by volume and the algorithm is applied to each group separately. Versions put into a bucket are not considered for later buckets even if the time interval overlaps. `benji enforce` uses the system's local time zone at invocation time to construct the buckets.

**Comment by kvaps** [comment] 2020-05-14 12:30
> As a workaround you could use weeks12 which is four versions per month for the last three months

Oh I totally confused now,  why `weeks12`  is meaning "four versions per month" but not "1 version per 12 weeks"?

> Could you tell me more about your use case please? And why weeks12 wouldn't be a suitable alternative? I'm trying to evaluate if such a new feature would be generally useful as it would introduced extra complexity into a sensitive area.

I need to keep latest 3 versions per month. Eg, I have monthly backups (one backup operation per month). But sometimes someone may create additional ones, without protecting first copy.

- I need to remove everything by retention, to keep only latest 3 copies. this is fine with `latest3`

- Another case: we have very dynamic structure, there might be newly created VMs and removed old ones each day. We need to store backup for removed VMs up to 1 month then remove it as unnecessary. Here `month1` is fine, but we want to keep more than 1 copy (if any)


> Without seeing all the versions I can't tell you why this specific version would be removed. But I can explain the intended behaviour of the two specifications you listed:
> 
>     * `weeks1,latest1`: Keep the youngest version and keep one version of the current week. This results in up to two remaining versions of a specific volume (apart from protected and incomplete versions which are not taken into account).
> 
>     * `days7,latest1`: Keep the youngest version and keep one version per day for the last seven days. This results in up to eight remaining versions.

Thanks for explanation, thus both of them should delete `2020-05-06T02:28:23` as it was 8 days ago, isn't it? Why `weeks1` is  still keeping that?

**Comment by elemental-lf** [comment] 2020-05-15 15:00
> > As a workaround you could use weeks12 which is four versions per month for the last three months
> 
> Oh I totally confused now, why `weeks12` is meaning "four versions per month" but not "1 version per 12 weeks"?

`weeks12` means that there are 12 buckets for the last 12 calendar weeks. Weeks start on Monday.
The versions of a volume are sorted into these buckets by their time of creation. And from each bucket the oldest version is kept. It must be the oldest and not the youngest otherwise this scheme would not work as versions would be deleted before they could get old enough for the next bucket.

As 12 weeks are three months this approximates your requirements. One wart is that it is based on calendar weeks and not calendar months.

> > Could you tell me more about your use case please? And why weeks12 wouldn't be a suitable alternative? I'm trying to evaluate if such a new feature would be generally useful as it would introduced extra complexity into a sensitive area.
> 
> I need to keep latest 3 versions per month. Eg, I have monthly backups (one backup operation per month). But sometimes someone may create additional ones, without protecting first copy.

Okay, that is indeed not possible now. It would be quite easy to keep the oldest three versions. But the latest/youngest three wouldn't fly with the current algorithm I think.

> Thanks for explanation, thus both of them should delete `2020-05-06T02:28:23` as it was 8 days ago, isn't it? Why `weeks1` is still keeping that?

It sounds like that. `benji --log-level DEBUG enforce --dry-run ...` might reveal some further information.

**Comment by elemental-lf** [comment] 2021-02-15 14:52
I'm going to close this issue as there has been no further discussion on it.

**Closed as completed by elemental-lf** 2021-02-15 14:52 UTC
Labels: feature
