### ISSUE TITLE
Can Benji do this?

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#34] opened 2019-04-02 10:58 UTC
We are interested in having powered off cold backup storage.  

We would have two completely different backup storage locations.  Only one would be powered on and in use, we would alternate them weekly. 

How would benji handle backing up in this scenario?  I am thinking we would need atleast 1 full backup on each storage location?   The biggest item in my head is how benji will know to create a full backup on the 2nd storage set once its introduced as a full backup will exist in the database on the 1st storage.  

Appreciate the input!

**Comment by elemental-lf** [comment] 2019-04-02 23:40
Block lookup and deduplication are per storage. If you specify alternating storages with the `-S` option of `benji backup` I think you will get exactly what you want. 
There is no concept of a full backup in Benji. During a backup if a block is not yet present in the storage it is saved to it and a pointer to the block is stored in the database. If it is already present then only a pointer to the existing block is stored in the database and nothing is written to the storage.

**Comment by adambmedent** [comment] 2019-04-03 10:41
Ok.  I guess I get confused because the way the documentation lays it out.  For example.

Benji does forward-incremental backups. In contrast to other backup modes, there is no need to create another full backup after the first one. From a restore standpoint all versions are full backups (sometimes called a synthetic full backup).

The 2nd and 3rd sentence are somewhat contradicting to me.  2nd sentence makes me feel like the first backup is a full and then everyone after is a incremental.

**Comment by adambmedent** [comment] 2019-04-03 11:56
I could totally be missing something, but testing is not working as expected.

Kick off first backup to storage1, all is well.  Kick off backup to storage2 and I get this error.

ERROR: An exception of type UsageError occurred: Base version and new version have to be in the same storage.

**Comment by adambmedent** [comment] 2019-04-03 14:31
It seems like the only way this will work is to not use differential backups at all and count on deduplication to deduplicate the blocks. 

Issue with this is its much harder on the storage and I don't know if it will really scale.  

Working on setting up a large scale test of some sort.

**Comment by elemental-lf** [comment] 2019-04-03 21:30
* Yes, you're right the wording in the documentation is misleading. I think I'll remove this paragraph completely.

* Regarding the "Base version and new version have to be in the same storage." error message: This is by design as you might have guessed. Without such a restriction blocks of one version could be scattered across multiple storages. If only one of these storages is unavailable then the version couldn't be restored.  And your usage scenario with alternating storages wouldn't work either...

* You can still use `rbd diff --from-snap`. You just have to keep two RBD snapshots, one for each storage. The scripts are not prepared for this but Benji itself has no problem it. Performance  would be reduced without the hints generated by  `rbd diff --from-snap`  as Benji would instead of only reading changed blocks always read all used blocks of an image which is why I'd recommend against it.

**Comment by adambmedent** [comment] 2019-04-04 10:00
> * Yes, you're right the wording in the documentation is misleading. I think I'll remove this paragraph completely.
> * Regarding the "Base version and new version have to be in the same storage." error message: This is by design as you might have guessed. Without such a restriction blocks of one version could be scattered across multiple storages. If only one of these storages is unavailable then the version couldn't be restored.  And your usage scenario with alternating storages wouldn't work either...
> * You can still use `rbd diff --from-snap`. You just have to keep two RBD snapshots, one for each storage. The scripts are not prepared for this but Benji itself has no problem it. Performance  would be reduced without the hints generated by  `rbd diff --from-snap`  as Benji would instead of only reading changed blocks always read all used blocks of an image which is why I'd recommend against it.

Ahhh now that makes more sense to me.  Going to start doing more testing right now.

**Comment by elemental-lf** [comment] 2019-04-04 10:53
I'll close this issue.

**Closed as completed by elemental-lf** 2019-04-04 10:53 UTC
Labels: user support
